
FLAGS = -DLINUX

OBJS = osdep.o amxconv_l.o amxconv.o main_sa.o 

ifdef DEBUG
	CFLAGS = -g -ggdb
else
	CFLAGS = -O3
endif

CFLAGS += -I../../commonlib/include
CXXFLAGS = $(CFLAGS)

LFLAGS = -L../../commonlib -lamcommon

.cc.o:
	$(CXX) -Wall $(CXXFLAGS) $(FLAGS) -o $@ -c $< 

.cpp.o:
	$(CXX) -Wall $(CXXFLAGS) $(FLAGS) -o $@ -c $< 

amxconvert: $(OBJS)
	$(CXX) -Wall -o $@ $(OBJS) $(LFLAGS) 

clean:
	rm -f *.o *~ amxconvert

