#!/bin/sh

TEMP=/tmp/tmp.gen.$$


cat $1 | grep SOURCE | grep -v pm_shared | grep "=.\\\\" | grep "cpp" | cut -f2 -d"\\" > $TEMP


cat $TEMP | cut -f1 -d"." | awk '{print "$(DLL_OBJDIR)/"$1".o \\"}' > $TEMP

cat $TEMP
rm $TEMP
